
//Asteroids

var asteroids_Char = new Array("Asteroid Belt - An asteroid field was a collection of asteroid clusters of different sizes, found throughout the galaxy. Asteroid fields were almost impossible to navigate through safely, because of their impredictability.", "Single Asteroid", "Asteroid Cluster", "Asteroid Base", "Belt Mining Colony", "Starport", "Hollow Asteroid", "Ice Asteroid", "Massive Asteroid Field - An asteroid field was a collection of asteroid clusters of different sizes, found throughout the galaxy. Asteroid fields were almost impossible to navigate through safely, because of their impredictability.",);
var asteroids_Atmo = new Array("Vacuum", "Thin");
var asteroids_Bios = new Array("Engineered", "Remnant", "Human-miscible", "Immiscible", "Microbial");
var asteroids_Popu = new Array("0", "1-10", "10-100");
var asteroids_Temp = new Array();


var planet_Char = new Array("Barren","Cold","Desert","Destroyed","Fluid","Frozen","Garden","Hell","Hospitable","Hot","Ice","Inferno","Inner","Inhospitable","Ocean","Rad","Storm","Temperate","Tropical","Tundra","Twilight Forest","Vacuum","Water","Dry","Deep Water","Extreme Depths","Clouds","Forest","Hills","High Altitude","Marsh","Urban","Gas",);
var planet_Atmo = new Array("Vacuum - The atmosphere has a pressure of less than 0.001 atmospheres, which requires the use of a vacc suit.","Very Thin - Very thin requires a respirator. The atmosphere has a pressure of 0.1 to 0.42 atmospheres, which requires the use of a respirator to ensure sufficient oxygen.","Thin - The atmosphere has a pressure of 0 43 to 0.70 atmospheres. The atmosphere is a standard oxygen/nitrogen mix, which is breathable without assistance.","Standard - The atmosphere is a standard oxygen/nitrogen mix, which is breathable without assistance.","Dense - The atmosphere is a standard oxygen/nitrogen mix, which is breathable without assistance.","Corrosive - A concentrated gas mix or unusual temperature creates a corrosive environment, which requires the use of a Hostile environment suit or vacc suit.","Toxic - A concentrated gas mix or unusual temperature creates a toxic environment, which requires the use of a Hostile environment suit or vacc suit.","Insideous - The atmosphere is similar to a corrosive atmosphere, but extreme conditions cause the corrosive effects to defeat any protective measures in 2 to 12 hours.",);
var planet_Bios = new Array("Engineered - Engineered biospheres are among the rarest, as they require enormous time and effort on the part of a highly advanced civilization. Whatever life exists on this planet has been extensively altered by an alien race or by advanced pretech gengineering methods.", "Remnant - Biosphere remnants are the wreckage of a ruined ecology. Petrified trees, drifts of preserved bones, forests of dead plant life; something killed all the life on this planet in the relatively recent past. It may have been the exercise of a maltech planet-buster weapon, or a mutant microbe introduced by human colonists, or some volcanic eruption or asteroid impact that plunged the world into decades of frozen night. Any local civilization not sophisticated enough to escape the planet likely died when it did. Their ruins and remains might be found throughout the desolate wastes, along with more clues as to the cause of the devastation.", "Human-miscible - Human-miscible biospheres are those in which some substantial portion of the native life is biologically compatible with human nutritional needs. Th e local plants and animals may not be tasty or terribly nourishing, but they can support life without the serious importation of Terran crop seeds and livestock.", "Immiscible - Immiscible biospheres are not friendly to humans. None of the local plants or animals are edible, and anything the colony needs to eat will have to be grown from Terran stock. Worse, it is common for the pollen and other microbial life of these worlds to be highly allergenic to humans, requiring the regular use of tailored antiallergenics to prevent eventual respiratory failure. These worlds are exceptionally susceptible to the temptation of human gengineering.", "Microbial - Microbial life can also be dangerous. While most alien microbes are unable to infect or harm the radically different biology of humans, some show enough ingenuity to accomplish even that difficult feat. Rumors of terrible “space plagues” that leave behind only drifting ships and garbled warnings remain a steady staple at spacer bars throughout the known universe.");
var planet_Popu = new Array("Alien civilizations are even rarer than massively human-populated planets, but they can be found in some sectors. On these worlds, any human presence is either nonexistent or simply a token contingent of traders and diplomats. The actual number of aliens may range from a few tens of thousands to teeming worlds of billions.", "No population - There might not even be population on a planet. It might be a barren rock with no atmosphere and no valuable resources to speak of or maybe it was a thriving colony one or a center of an ancient civilization. Perhaps all the colonists abandoned the rock after a corporate gold rush had run it's course.", "Outposts are rarely composed of more than a few hundred or few thousand colonists at the most. Outposts are either very new colonies that have not have the requisite time to grow or they are uncolonized worlds that just happen to have a naval or corporate base on the surface. Corporate or military outposts aren’t intended to be completely self- sufficient. While large outposts are often forced to raise their own food supplies, replacement personnel, spare parts, and advanced tech must all be brought in from elsewhere.", "Tens of thousands of inhabitants are often found on newly- colonized worlds, or those with limited arable land. With such a small population, most settlements tend to be clustered close to one another for mutual support and efficient exploitation of land. The atmosphere can be something like that of a village-dotted countryside, with too few people to support large, specialized cities. The major settlement of the planet is usually built around the spaceport. Politics on planets with so few people tend to be very personal in nature.", "Hundreds of thousands of inhabitants make up the population of most frontier worlds, usually ones with adequate supplies of arable land and surface conditions amenable to a human without a vacc suit or filter mask. This level of population is also usually the most that a world at tech level 4 can support using only artificial hydroponic complexes and sealed agricultural systems, so less hospitable planets rarely have more than this many inhabitants. At this level of population, city-states and hub settlements start to form, and some political divisions might exist beneath the overall planetary government.", "Millions of inhabitants are found on some of the more populous frontier worlds, those planets with an excellent climate and soil for agriculture. These worlds teem with human life compared to most of their neighbors, and if they have suffi  cient technological expertise to build spike drives, they probably are one of the more powerful planets in the sector.",);
var planet_Temp = new Array();
















